version: '3'  # Docker Composeのバージョン
services:
  db:
    image: postgres
    ports: 
      - "5432"
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:  # コンテナに名前をつける
    build: .  # Dockerfileがあるディレクトリへのパス
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code  # ホストPCのカレントディレクトリとコンテナ内のcodeディレクトリを同期させる
    ports:
      - "8000:8000"
    depends_on:
      - db